# fly.toml app configuration file generated for nts-films-crm on 2026-02-11T13:33:24-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nts-films-crm'
primary_region = 'lax'

[build]

[env]
  DATABASE_PATH = '/data/ntsfilms.db'
  NODE_ENV = 'production'
  PORT = '8080'
  UPLOAD_DIR = '/data/uploads'

[[mounts]]
  source = 'ntsfilms_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = '1gb'
  cpus = 1
  memory_mb = 1024
